# Generated by Django 4.1.1 on 2022-11-07 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'livro', 'verbose_name_plural': 'livros'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Autor Sem Nome', max_length=200, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='current_page',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='página atual'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Sem Título', max_length=200, verbose_name='título'),
        ),
    ]
