# Generated by Django 4.1.2 on 2022-11-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_remove_myuser_theme_myuser_contrast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='dyslexic',
            field=models.BooleanField(default=False),
        ),
    ]
