# Generated by Django 4.1.1 on 2022-11-05 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0004_alter_myuser_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='font_size',
            field=models.FloatField(default=13, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
