# Generated by Django 4.1.2 on 2022-11-07 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0005_alter_myuser_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='font_size',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
