# Generated by Django 4.1.1 on 2022-11-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0006_alter_myuser_font_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='endereço de e-mail'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
    ]
